### ISSUE TITLE
Community Health

### ISSUE THREAD

**Issue by huwaireb** [typst-community/.github#10]
[Community Health Guideline Doc](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)

### TODO
- [X] CODE_OF_CONDUCT.md
- [X] SECURITY.md

**Comment by jcbhmr** [comment]
i would recommend: dont worry about governance or security or code_of_conduct or anything _until you need it_. once an issue like "i have found a security issue" happens or a flame war happens or governance is questioned _then_ draw these things up. why then and not now? you'll have clear "we need to solve this problem" instead of whiteboard-abstract "well we _might_ have questions about who maintains which repos so lets debate and whiteboard that" 🤷‍♂️

actual advice to accomplish those tasks: i suggest enabling github's security reporting on all present and future repos. that takes care of security.md and any related stuff.

![image](https://github.com/typst-community/.github/assets/61068799/414e46a2-993e-46a5-b1f5-605835377ad3)
https://github.com/organizations/typst-community/settings/security_analysis 👈

for governance, id just put a blurb in the readme saying "decisions are made by [BDFL huwaireb](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life)" or something until growth happens lol

**Comment by huwaireb** [comment]
@jcbhmr, sounds great. I've enabled that security setting and added a default SECURITY.md that is quite generic. 

GOVERNANCE.md or similar can probably go into the new [organization](https://github.com/typst-community/organization) I created, should also have things like GETTING_INVOLVED and others. I'll leave this repository for github org-wide files. I dont think BDFL is appropriate, but that's up for a later discussion in [organization](https://github.com/typst-community/organization) repo.
